'use client';
import { useCallback,useEffect,useState } from 'react';
import { Bell,Check,CheckCheck,Clock3,Download,FileText,MessageSquare,Plus,Printer,RefreshCw,ShieldCheck,AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { Skeleton } from '@/components/ui/skeleton';
import { BUCKET_NAMES,NOTE_NAMES,RESOLUTION_NAMES,type Brand,type FileDetail } from '@/lib/domain';
import { extractPdf } from '@/lib/pdf-client';
import { api,post,n,date } from '@/lib/client';
import { Picker,Blank } from './controls';
import { AuditList } from './activity-view';
export default function FilePanel({id,brands,onClose,onChange,onOpenFile}:{id:string|null;brands:Brand[];onClose:()=>void;onChange:()=>Promise<void>;onOpenFile:(id:string)=>void}){
  const [data,setData]=useState<FileDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview'),[printing,setPrinting]=useState(false),[resolveIds,setResolveIds]=useState<string[]>([]),[resolution,setResolution]=useState('false_alarm'),[resolutionNote,setResolutionNote]=useState(''),[noteRef,setNoteRef]=useState(''),[noteType,setNoteType]=useState('other'),[noteBody,setNoteBody]=useState(''),[manualBucket,setManualBucket]=useState('single'),[manualNote,setManualNote]=useState(''),[limit,setLimit]=useState(40),[orderQuery,setOrderQuery]=useState('');
  const refresh=useCallback(async()=>{if(id)setData(await api<FileDetail>(`files/${id}`));},[id]);
  useEffect(()=>{setData(null);setError('');setTab('overview');setLimit(40);setOrderQuery('');setNoteRef('');setNoteBody('');setManualNote('');if(id)void refresh().catch(e=>setError(e.message));},[id,refresh]);
  async function run(action:()=>Promise<unknown>,message:string){setBusy(true);try{await action();await Promise.all([refresh(),onChange()]);toast.success(message);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
  async function recheck(){if(!id)return;await run(async()=>{const res=await fetch(`/api/files/${id}/download?purpose=inspect`);if(!res.ok)throw new Error('تعذر تحميل الملف لإعادة الفحص.');const pages=await extractPdf(await res.blob(),brands,()=>{});await post(`files/${id}/process`,{pages});},'اكتمل فحص الملف');}
  const file=data?.file,brand=brands.find(b=>b.id===file?.brand_id),openIssues=data?.findings.filter(i=>i.status==='open')??[],attention=data?.notes.filter(note=>note.ref)??[],unknown=openIssues.filter(i=>['brand_unknown','quantity_unknown'].includes(i.kind));
  return <><Sheet open={!!id} onOpenChange={v=>{if(!v)onClose();}}><SheetContent side="left" className="file-panel" dir="rtl"><SheetHeader><SheetTitle>{file?.name??'تفاصيل الملف'}</SheetTitle><SheetDescription>{brand?.name??'البوالص'}{file?` · رُفع ${date(file.uploaded_at,true)}`:''}</SheetDescription></SheetHeader><div className="panel-scroll">{error?<div className="error-banner">{error}</div>:!data?<Skeleton className="h-72 w-full"/>:<>
      <div className="file-summary"><span className="pdf-icon large"><FileText/><small>PDF</small></span><div><strong>{n(file!.waybill_count)} بوليصة</strong><span>{n(file!.page_count)} صفحة · {file!.carriers.join('، ')}</span></div><Badge className={`bucket-badge bucket-${file!.bucket}`}>{BUCKET_NAMES[file!.bucket]}</Badge></div>
      {file!.changed_version>file!.ack_version&&<div className="late-alert"><Bell/><div><strong>تعديل بعد الطباعة</strong><p>راجع الملاحظات وتعامل مع الملصقات المطبوعة قبل متابعة التجهيز.</p><Button variant="outline" size="sm" disabled={busy} onClick={()=>void run(()=>post(`files/${id}/acknowledge`,{version:file!.changed_version}),'تم تأكيد مراجعة التغييرات')}><CheckCheck/> راجعت التعديلات</Button></div></div>}
      {attention.length>0&&<div className="attention-strip"><strong>طلبات تحتاج انتباهًا</strong><div>{[...new Set(attention.map(note=>note.ref))].map(ref=><button key={ref} dir="ltr" onClick={()=>{setTab('notes');setNoteRef(ref!);}}>{ref}</button>)}</div></div>}
      <div className="file-actions"><Button asChild variant="outline"><a href={`/api/files/${id}/download?inline=1`} target="_blank" rel="noreferrer"><Printer/> فتح للطباعة</a></Button><Button asChild variant="outline"><a href={`/api/files/${id}/download`}><Download/> تنزيل الأصلي</a></Button><Button disabled={busy||file!.status!=='ready'||openIssues.length>0} onClick={()=>setPrinting(true)}><Check/> تأكيد الطباعة</Button></div><p className="microcopy">فتح الملف لا يغيّر حالته. أكد الطباعة بعد إتمامها.</p>
      <div className="stage-picker"><span>المرحلة الحالية</span><Picker label="نقل الملف" value={file!.stage} disabled={busy} onChange={stage=>{if(stage==='printed'){setPrinting(true);return;}void run(()=>post(`files/${id}/move`,{stage}),'تم نقل الملف');}} options={brand?.columns.map(c=>({value:c.id,label:c.name}))??[]}/></div>
      {file!.detected_brand_id&&file!.detected_brand_id!==file!.brand_id&&<div className="error-banner"><strong>الملف يطابق علامة {brands.find(b=>b.id===file!.detected_brand_id)?.name}</strong><Button size="sm" variant="outline" disabled={busy} onClick={()=>void run(()=>post(`files/${id}/brand`,{brandId:file!.detected_brand_id}),'نُقل الملف وأُعيد فحصه')}>نقل إلى العلامة الصحيحة</Button></div>}
      <Tabs dir="rtl" value={tab} onValueChange={setTab}><TabsList className="detail-tabs"><TabsTrigger value="overview">الفحص والطلبات{openIssues.length>0&&<span>{n(openIssues.length)}</span>}</TabsTrigger><TabsTrigger value="notes">الملاحظات <span>{n(data.notes.length)}</span></TabsTrigger><TabsTrigger value="history">النشاط</TabsTrigger></TabsList>
      <TabsContent value="overview"><div className="section-title"><h3>نتيجة الفحص</h3><Button size="sm" variant="ghost" disabled={busy||!file!.hash} onClick={()=>void recheck()}><RefreshCw className={busy?'spin':''} size={15}/> إعادة الفحص</Button></div>{file!.status!=='ready'&&<div className="warning-banner">لم يكتمل الفحص. إذا اكتمل رفع الملف، يمكنك استئناف الفحص من الزر أعلاه.</div>}{openIssues.length===0&&file!.status==='ready'?<div className="success-banner"><ShieldCheck size={20}/><div><strong>لا توجد تنبيهات مفتوحة</strong><span>تم فحص جميع الصفحات ومراجعة النتائج.</span></div></div>:<>{openIssues.length>0&&<div className="issues-heading"><span>{n(openIssues.length)} تنبيه يحتاج مراجعة</span><Button size="sm" variant="outline" onClick={()=>{setResolveIds(openIssues.slice(0,1000).map(i=>i.id));setResolutionNote('');}}>معالجة التنبيهات المفتوحة</Button></div>}{unknown.length>0&&<div className="manual-confirm"><strong>تأكيد البيانات غير الظاهرة في البوليصة</strong><p>بعض الصفحات لا تذكر العلامة أو عدد المنتجات بوضوح. أكدها بعد مراجعة الأصل.</p><Picker label="مجموعة الكمية" value={manualBucket} onChange={setManualBucket} options={[{value:'single',label:'حبة واحدة'},{value:'multiple',label:'حبتان أو أكثر'}]}/><Input placeholder="ملاحظة المراجعة" aria-label="ملاحظة التأكيد اليدوي" value={manualNote} onChange={e=>setManualNote(e.target.value)}/><Button size="sm" disabled={busy||!manualNote.trim()} onClick={()=>void run(()=>post(`files/${id}/confirm`,{bucket:manualBucket,note:manualNote}),'تم تسجيل التأكيد اليدوي')}>تأكيد علامة {brand?.name} والكمية</Button></div>}{openIssues.slice(0,limit).map(issue=><div className="finding" key={issue.id}><AlertTriangle size={17}/><div><p>{issue.message}</p><div className="finding-meta">{issue.ref&&<span>الطلب <bdi>{issue.ref}</bdi></span>}{issue.page&&<span>صفحة {n(issue.page)}</span>}{issue.related_name&&<button onClick={()=>onOpenFile(issue.related_file_id!)}>{issue.related_name}{issue.related_page?` · صفحة ${n(issue.related_page)}`:''}{issue.related_uploaded_at?` · ${date(issue.related_uploaded_at)}`:''}</button>}</div></div><Button variant="ghost" size="sm" onClick={()=>{setResolveIds([issue.id]);setResolutionNote('');}}>معالجة</Button></div>)}{openIssues.length>limit&&<Button variant="ghost" onClick={()=>setLimit(v=>v+100)}>عرض مزيد من التنبيهات</Button>}</>}
      <div className="section-title"><h3>الطلبات والصفحات</h3><Input className="order-filter" dir="ltr" placeholder="Ref" aria-label="تصفية أرقام الطلبات" value={orderQuery} onChange={e=>setOrderQuery(e.target.value)}/></div><Table><TableHeader><TableRow><TableHead>الطلب</TableHead><TableHead>الصفحة</TableHead><TableHead>الكمية</TableHead><TableHead>الشركة / التتبع</TableHead></TableRow></TableHeader><TableBody>{data.orders.filter(o=>o.ref.includes(orderQuery)).slice(0,limit).map(o=><TableRow key={`${o.page}-${o.ref}`}><TableCell><button className="ref-link" dir="ltr" onClick={()=>{setNoteRef(o.ref);setTab('notes');}}>{o.ref}</button>{o.page_role==='support'&&<small className="support-label">مستند مرافق</small>}</TableCell><TableCell>{n(o.page)}</TableCell><TableCell>{o.quantity===null?'غير مذكورة':n(o.quantity)}</TableCell><TableCell><span>{o.carrier}</span><small className="tracking" dir="ltr">{o.tracking??'—'}</small></TableCell></TableRow>)}</TableBody></Table>{data.orders.filter(o=>o.ref.includes(orderQuery)).length>limit&&<Button variant="ghost" onClick={()=>setLimit(v=>v+100)}>عرض المزيد من الطلبات</Button>}{data.findings.some(i=>i.status!=='open')&&<details className="resolved-findings"><summary>تنبيهات تمت معالجتها ({n(data.findings.filter(i=>i.status!=='open').length)})</summary>{data.findings.filter(i=>i.status!=='open').slice(0,100).map(i=><div key={i.id}><strong>{RESOLUTION_NAMES[i.status]??i.status}</strong> · {i.ref??'الملف'}<p>{i.resolution_note}</p></div>)}</details>}</TabsContent>
      <TabsContent value="notes"><form className="note-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await post(`files/${id}/notes`,{ref:noteRef.trim()||null,type:noteType,body:noteBody});setNoteBody('');},'تمت إضافة الملاحظة');}}><h3>إضافة ملاحظة</h3><div className="form-row"><label>رقم الطلب (اختياري)<Input dir="ltr" value={noteRef} onChange={e=>setNoteRef(e.target.value)} placeholder="اتركه فارغًا للملاحظات العامة"/></label><label>نوع الملاحظة<Picker label="نوع الملاحظة" value={noteType} onChange={setNoteType} options={Object.entries(NOTE_NAMES).map(([value,label])=>({value,label}))}/></label></div><Textarea aria-label="نص الملاحظة" placeholder="ما الذي يحتاج الفريق إلى معرفته؟" value={noteBody} onChange={e=>setNoteBody(e.target.value)} required maxLength={4000}/><Button disabled={busy||!noteBody.trim()}><Plus size={16}/> إضافة الملاحظة</Button></form>{data.notes.length===0?<Blank title="لا توجد ملاحظات بعد" icon={MessageSquare}/>:data.notes.map(note=><div className={`note note-${note.type}`} key={note.id}><div><Badge variant="outline">{NOTE_NAMES[note.type]}</Badge><strong>{note.ref?<bdi>{note.ref}</bdi>:'ملاحظة عامة'}</strong><span>{date(note.created_at,true)}</span></div><p>{note.body}</p><small>{note.actor_name}</small></div>)}<Button variant="outline" onClick={()=>window.open(`/attention?file=${encodeURIComponent(id!)}`,'_blank','noopener,noreferrer')}><Printer size={16}/> طباعة ورقة التنبيهات</Button></TabsContent>
      <TabsContent value="history"><AuditList events={data.audit}/></TabsContent></Tabs><div className="expiry-line"><Clock3 size={14}/> يُحذف الملف عند انتهاء الاحتفاظ في {date(file!.expires_at,true)}</div>
    </>}</div></SheetContent></Sheet>
    <AlertDialog open={printing} onOpenChange={setPrinting}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>هل اكتملت طباعة الملف؟</AlertDialogTitle><AlertDialogDescription>سيُسجل اسمك ووقت الطباعة، وستظهر أي ملاحظات لاحقة كتنبيه للفريق.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>لم أطبع بعد</AlertDialogCancel><AlertDialogAction disabled={busy||openIssues.length>0||file?.status!=='ready'} onClick={()=>void run(()=>post(`files/${id}/printed`,{}),'تم تأكيد الطباعة')}>نعم، تمت الطباعة</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={resolveIds.length>0} onOpenChange={v=>{if(!v)setResolveIds([]);}}><DialogContent dir="rtl"><DialogHeader><DialogTitle>معالجة {n(resolveIds.length)} تنبيه</DialogTitle><DialogDescription>سجل النتيجة والإجراء المتخذ. معالجة التنبيه لا تحذف صفحات من PDF.</DialogDescription></DialogHeader><Picker label="نتيجة المراجعة" value={resolution} onChange={setResolution} options={Object.entries(RESOLUTION_NAMES).map(([value,label])=>({value,label}))}/><Textarea aria-label="ملاحظة معالجة التنبيه" value={resolutionNote} onChange={e=>setResolutionNote(e.target.value)} placeholder="مثال: إعادة طباعة مقصودة، وتم استبعاد الملصق السابق"/><Button disabled={busy||!resolutionNote.trim()} onClick={()=>void run(async()=>{await post('findings',{ids:resolveIds,status:resolution,note:resolutionNote});setResolveIds([]);},'تم تسجيل المعالجة')}>حفظ المعالجة</Button></DialogContent></Dialog>
  </>;
}
