'use client';
import { useCallback,useEffect,useState } from 'react';
import { Search,ListChecks } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Table,TableHeader,TableBody,TableRow,TableHead,TableCell } from '@/components/ui/table';
import { Skeleton } from '@/components/ui/skeleton';
import { api,post,n,date,stageName } from '@/lib/client';
import type { Brand,Occurrence } from '@/lib/domain';
import { Blank } from './controls';
export default function SearchView({brands,onOpen,initialQuery=''}:{brands:Brand[];onOpen:(id:string)=>void;initialQuery?:string}){
  const [mode,setMode]=useState('single'),[query,setQuery]=useState(initialQuery),[batch,setBatch]=useState(''),[results,setResults]=useState<Occurrence[]>([]),[missing,setMissing]=useState<string[]>([]),[searched,setSearched]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[truncated,setTruncated]=useState(false);
  const runSearch=useCallback(async(q:string,list=false)=>{setBusy(true);setError('');try{const data=list?await post<{results:Occurrence[];missing:string[];truncated:boolean}>('search',{refs:q}):await api<{results:Occurrence[];missing:string[];truncated:boolean}>(`search?q=${encodeURIComponent(q)}`);setResults(data.results);setMissing(data.missing);setTruncated(data.truncated);setSearched(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[]);
  useEffect(()=>{if(initialQuery){setQuery(initialQuery);void runSearch(initialQuery);}},[initialQuery,runSearch]);
  return <div className="page-content narrow-page"><div className="page-heading"><div><div className="eyebrow">كل العلامات في مكان واحد</div><h1>أين يوجد الطلب؟</h1><p>ابحث برقم الطلب أو جزء منه، وستظهر كل الملفات والصفحات المرتبطة به.</p></div><Search className="page-heading-icon"/></div><div className="search-surface"><Tabs dir="rtl" value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="single"><Search size={16}/> طلب واحد</TabsTrigger><TabsTrigger value="batch"><ListChecks size={16}/> فحص قائمة</TabsTrigger></TabsList><TabsContent value="single"><form className="search-form" onSubmit={e=>{e.preventDefault();void runSearch(query);}}><Input dir="ltr" aria-label="رقم الطلب للبحث" placeholder="مثال: 288365535" value={query} onChange={e=>setQuery(e.target.value)} minLength={2} maxLength={40}/><Button disabled={busy||query.trim().length<2}><Search size={17}/> بحث</Button></form></TabsContent><TabsContent value="batch"><form onSubmit={e=>{e.preventDefault();void runSearch(batch,true);}}><Textarea dir="ltr" aria-label="قائمة أرقام الطلبات" placeholder={'288365535\n289691732'} value={batch} onChange={e=>setBatch(e.target.value)} maxLength={12000}/><div className="batch-footer"><span>رقم في كل سطر، حتى ٥٠٠ طلب.</span><Button disabled={busy||!batch.trim()}><ListChecks/> فحص القائمة</Button></div></form></TabsContent></Tabs></div>{error&&<div className="error-banner">{error}</div>}{busy?<Skeleton className="h-64 w-full"/>:!searched?<Blank title="ابدأ برقم الطلب" description="يشمل البحث جميع العلامات والملفات المحفوظة، بما فيها الأرشيف." icon={Search}/>:<>{missing.length>0&&<div className="warning-banner"><strong>لم نجد {n(missing.length)} طلبًا في الملفات المحفوظة</strong><div className="missing-refs">{missing.map(ref=><code key={ref}>{ref}</code>)}</div></div>}{truncated&&<div className="warning-banner">النتائج كثيرة. أدخل رقمًا أطول لتحديد البحث.</div>}{results.length===0?<Blank title="لا توجد نتائج مطابقة" description="تحقق من رقم الطلب أو من انتهاء مدة الاحتفاظ بالملف." icon={Search}/>:<div className="results-surface"><div className="section-title"><h3>{n(results.length)} نتيجة</h3></div><Table><TableHeader><TableRow><TableHead>رقم الطلب</TableHead><TableHead>العلامة / الملف</TableHead><TableHead>الصفحة</TableHead><TableHead>تاريخ الرفع</TableHead><TableHead>الحالة</TableHead><TableHead/></TableRow></TableHeader><TableBody>{results.map((r,i)=><TableRow key={`${r.file_id}-${r.page}-${r.ref}-${i}`}><TableCell><bdi className="ref-number">{r.ref}</bdi></TableCell><TableCell><strong>{r.brand_name}</strong><small className="table-file-name">{r.name}</small></TableCell><TableCell>{n(r.page)}</TableCell><TableCell>{r.uploaded_at?date(r.uploaded_at):'—'}</TableCell><TableCell>{r.historical?'انتهى حفظ PDF':stageName(r.stage??'',brands,r.brand_id)}</TableCell><TableCell>{r.file_id&&<Button variant="outline" size="sm" onClick={()=>onOpen(r.file_id)}>فتح الملف</Button>}</TableCell></TableRow>)}</TableBody></Table></div>}</>}</div>;
}
