import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', { id: text('id').primaryKey(), email: text('email').notNull().unique(), name: text('name').notNull(), role: text('role').notNull().default('operator'), active: integer('active').notNull().default(1), createdAt: text('created_at').notNull() });
export const brands = sqliteTable('brands', { id: text('id').primaryKey(), name: text('name').notNull(), color: text('color').notNull(), identifiers: text('identifiers').notNull(), columns: text('columns').notNull(), retentionDays: integer('retention_days').notNull().default(30), archiveDays: integer('archive_days').notNull().default(7), indexDays: integer('index_days').notNull().default(0), createdAt: text('created_at').notNull() });
export const files = sqliteTable('files', { id: text('id').primaryKey(), brandId: text('brand_id').notNull().references(() => brands.id), name: text('name').notNull(), size: integer('size').notNull(), hash: text('hash'), objectKey: text('object_key').notNull(), status: text('status').notNull().default('uploading'), stage: text('stage').notNull().default('awaiting'), bucket: text('bucket').notNull().default('unknown'), detectedBrandId: text('detected_brand_id'), pageCount: integer('page_count').notNull().default(0), waybillCount: integer('waybill_count').notNull().default(0), carriers: text('carriers').notNull().default('[]'), uploadedAt: text('uploaded_at').notNull(), expiresAt: text('expires_at').notNull(), printedAt: text('printed_at'), shippedAt: text('shipped_at'), changedVersion: integer('changed_version').notNull().default(0), ackVersion: integer('ack_version').notNull().default(0), reviewedAt: text('reviewed_at'), createdBy: text('created_by').notNull(), processedAt: text('processed_at') }, t => [index('idx_files_brand_expiry').on(t.brandId,t.expiresAt), index('idx_files_brand_hash').on(t.brandId,t.hash)]);
export const pages = sqliteTable('pages', { id: text('id').primaryKey(), fileId: text('file_id').notNull().references(() => files.id, {onDelete:'cascade'}), page: integer('page').notNull(), data: text('data').notNull() }, t => [uniqueIndex('idx_pages_file_page').on(t.fileId,t.page)]);
export const occurrences = sqliteTable('occurrences', { id: text('id').primaryKey(), fileId: text('file_id').notNull().references(() => files.id, {onDelete:'cascade'}), brandId: text('brand_id').notNull(), page: integer('page').notNull(), ref: text('ref').notNull(), tracking: text('tracking'), quantity: integer('quantity'), carrier: text('carrier').notNull(), sourceDate: text('source_date'), dateType: text('date_type'), pageRole: text('page_role').notNull() }, t => [index('idx_occurrences_brand_ref').on(t.brandId,t.ref),index('idx_occurrences_file').on(t.fileId)]);
export const findings = sqliteTable('findings', { id: text('id').primaryKey(), fingerprint: text('fingerprint').notNull().unique(), fileId: text('file_id').notNull().references(() => files.id,{onDelete:'cascade'}), kind: text('kind').notNull(), ref: text('ref'), page: integer('page'), relatedFileId: text('related_file_id'), relatedPage: integer('related_page'), message: text('message').notNull(), status: text('status').notNull().default('open'), resolutionNote: text('resolution_note'), resolvedBy: text('resolved_by'), resolvedAt: text('resolved_at'), createdAt: text('created_at').notNull() }, t => [index('idx_findings_file_status').on(t.fileId,t.status)]);
export const notes = sqliteTable('notes', { id: text('id').primaryKey(), brandId: text('brand_id').notNull(), fileId: text('file_id'), ref: text('ref'), type: text('type').notNull(), body: text('body').notNull(), createdBy: text('created_by').notNull(), actorName: text('actor_name').notNull(), createdAt: text('created_at').notNull() },t => [index('idx_notes_brand_ref').on(t.brandId,t.ref),index('idx_notes_file').on(t.fileId)]);
export const audit = sqliteTable('audit', { id: text('id').primaryKey(), brandId: text('brand_id'), fileId: text('file_id'), action: text('action').notNull(), actorId: text('actor_id').notNull(), actorName: text('actor_name').notNull(), detail: text('detail').notNull(), createdAt: text('created_at').notNull() },t => [index('idx_audit_brand_date').on(t.brandId,t.createdAt),index('idx_audit_file').on(t.fileId)]);
export const orderIndex = sqliteTable('order_index', { id: text('id').primaryKey(), brandId: text('brand_id').notNull(), ref: text('ref').notNull(), fileName: text('file_name').notNull(), page: integer('page').notNull(), uploadedAt: text('uploaded_at').notNull(), stage: text('stage').notNull(), expiresAt: text('expires_at').notNull() },t=>[index('idx_order_index_ref').on(t.ref)]);
export const settings = sqliteTable('settings', { key: text('key').primaryKey(), value: text('value').notNull() });
